export const countryToRegion: Record<string, string> = {
    "Afghanistan": "Asia",
    "Albania": "Europe",
    "Algeria": "Africa",
    "Andorra": "Europe",
    "Angola": "Africa",
    "Antigua and Barbuda": "North America",
    "Argentina": "Latin America",
    "Armenia": "Asia",
    "Australia": "Oceania",
    "Austria": "Europe",
    "Azerbaijan": "Asia",
    "Bahamas": "North America",
    "Bahrain": "Middle East",
    "Bangladesh": "Asia",
    "Barbados": "North America",
    "Belarus": "Europe",
    "Belgium": "Europe",
    "Belize": "Latin America",
    "Benin": "Africa",
    "Bhutan": "Asia",
    "Bolivia": "Latin America",
    "Bosnia and Herzegovina": "Europe",
    "Botswana": "Africa",
    "Brazil": "Latin America",
    "Brunei": "Asia",
    "Bulgaria": "Europe",
    "Burkina Faso": "Africa",
    "Burundi": "Africa",
    "Cabo Verde": "Africa",
    "Cambodia": "Asia",
    "Cameroon": "Africa",
    "Canada": "North America",
    "Central African Republic": "Africa",
    "Chad": "Africa",
    "Chile": "Latin America",
    "China": "Asia",
    "Colombia": "Latin America",
    "Comoros": "Africa",
    "Congo (Congo-Brazzaville)": "Africa",
    "Costa Rica": "Latin America",
    "Croatia": "Europe",
    "Cuba": "Latin America",
    "Cyprus": "Europe",
    "Czechia (Czech Republic)": "Europe",
    "Denmark": "Europe",
    "Djibouti": "Africa",
    "Dominica": "North America",
    "Dominican Republic": "Latin America",
    "Ecuador": "Latin America",
    "Egypt": "Middle East",
    "El Salvador": "Latin America",
    "Equatorial Guinea": "Africa",
    "Eritrea": "Africa",
    "Estonia": "Europe",
    "Eswatini": "Africa",
    "Ethiopia": "Africa",
    "Fiji": "Oceania",
    "Finland": "Europe",
    "France": "Europe",
    "Gabon": "Africa",
    "Gambia": "Africa",
    "Georgia": "Asia",
    "Germany": "Europe",
    "Ghana": "Africa",
    "Greece": "Europe",
    "Grenada": "North America",
    "Guatemala": "Latin America",
    "Guinea": "Africa",
    "Guinea-Bissau": "Africa",
    "Guyana": "Latin America",
    "Haiti": "Latin America",
    "Honduras": "Latin America",
    "Hungary": "Europe",
    "Iceland": "Europe",
    "India": "Asia",
    "Indonesia": "Asia",
    "Iran": "Middle East",
    "Iraq": "Middle East",
    "Ireland": "Europe",
    "Israel": "Middle East",
    "Italy": "Europe",
    "Jamaica": "Latin America",
    "Japan": "Asia",
    "Jordan": "Middle East",
    "Kazakhstan": "Asia",
    "Kenya": "Africa",
    "Kiribati": "Oceania",
    "Korea (North)": "Asia",
    "Korea (South)": "Asia",
    "Kosovo": "Europe",
    "Kuwait": "Middle East",
    "Kyrgyzstan": "Asia",
    "Laos": "Asia",
    "Latvia": "Europe",
    "Lebanon": "Middle East",
    "Lesotho": "Africa",
    "Liberia": "Africa",
    "Libya": "Africa",
    "Liechtenstein": "Europe",
    "Lithuania": "Europe",
    "Luxembourg": "Europe",
    "Madagascar": "Africa",
    "Malawi": "Africa",
    "Malaysia": "Asia",
    "Maldives": "Asia",
    "Mali": "Africa",
    "Malta": "Europe",
    "Marshall Islands": "Oceania",
    "Mauritania": "Africa",
    "Mauritius": "Africa",
    "Mexico": "Latin America",
    "Micronesia": "Oceania",
    "Moldova": "Europe",
    "Monaco": "Europe",
    "Mongolia": "Asia",
    "Montenegro": "Europe",
    "Morocco": "Africa",
    "Mozambique": "Africa",
    "Myanmar (formerly Burma)": "Asia",
    "Namibia": "Africa",
    "Nauru": "Oceania",
    "Nepal": "Asia",
    "Netherlands": "Europe",
    "New Zealand": "Oceania",
    "Nicaragua": "Latin America",
    "Niger": "Africa",
    "Nigeria": "Africa",
    "North Macedonia": "Europe",
    "Norway": "Europe",
    "Oman": "Middle East",
    "Pakistan": "Asia",
    "Palau": "Oceania",
    "Palestine State": "Middle East",
    "Panama": "Latin America",
    "Papua New Guinea": "Oceania",
    "Paraguay": "Latin America",
    "Peru": "Latin America",
    "Philippines": "Asia",
    "Poland": "Europe",
    "Portugal": "Europe",
    "Qatar": "Middle East",
    "Romania": "Europe",
    "Russia": "Europe",
    "Rwanda": "Africa",
    "Saint Kitts and Nevis": "North America",
    "Saint Lucia": "North America",
    "Saint Vincent and the Grenadines": "North America",
    "Samoa": "Oceania",
    "San Marino": "Europe",
    "Sao Tome and Principe": "Africa",
    "Saudi Arabia": "Middle East",
    "Senegal": "Africa",
    "Serbia": "Europe",
    "Seychelles": "Africa",
    "Sierra Leone": "Africa",
    "Singapore": "Asia",
    "Slovakia": "Europe",
    "Slovenia": "Europe",
    "Solomon Islands": "Oceania",
    "Somalia": "Africa",
    "South Africa": "Africa",
    "South Sudan": "Africa",
    "Spain": "Europe",
    "Sri Lanka": "Asia",
    "Sudan": "Africa",
    "Suriname": "Latin America",
    "Sweden": "Europe",
    "Switzerland": "Europe",
    "Syria": "Middle East",
    "Taiwan": "Asia",
    "Tajikistan": "Asia",
    "Tanzania": "Africa",
    "Thailand": "Asia",
    "Timor-Leste": "Asia",
    "Togo": "Africa",
    "Tonga": "Oceania",
    "Trinidad and Tobago": "Latin America",
    "Tunisia": "Africa",
    "Turkey": "Middle East",
    "Turkmenistan": "Asia",
    "Tuvalu": "Oceania",
    "Uganda": "Africa",
    "Ukraine": "Europe",
    "United Arab Emirates": "Middle East",
    "United Kingdom": "Europe",
    "United States of America": "North America",
    "Uruguay": "Latin America",
    "Uzbekistan": "Asia",
    "Vanuatu": "Oceania",
    "Vatican City": "Europe",
    "Venezuela": "Latin America",
    "Vietnam": "Asia",
    "Yemen": "Middle East",
    "Zambia": "Africa",
    "Zimbabwe": "Africa"
};

const defaultTimezones: Record<string, string> = {
    "Afghanistan": "GMT+4:30",
    "Albania": "GMT+1",
    "Algeria": "GMT+1",
    "Andorra": "GMT+1",
    "Angola": "GMT+1",
    "Antigua and Barbuda": "GMT-4",
    "Argentina": "GMT-3",
    "Armenia": "GMT+4",
    "Australia": "GMT+10", // Default (Sydney/Melbourne)
    "Austria": "GMT+1",
    "Azerbaijan": "GMT+4",
    "Bahamas": "GMT-5",
    "Bahrain": "GMT+3",
    "Bangladesh": "GMT+6",
    "Barbados": "GMT-4",
    "Belarus": "GMT+3",
    "Belgium": "GMT+1",
    "Belize": "GMT-6",
    "Benin": "GMT+1",
    "Bhutan": "GMT+6",
    "Bolivia": "GMT-4",
    "Bosnia and Herzegovina": "GMT+1",
    "Botswana": "GMT+2",
    "Brazil": "GMT-3", // Default (Brasilia)
    "Brunei": "GMT+8",
    "Bulgaria": "GMT+2",
    "Burkina Faso": "GMT+0",
    "Burundi": "GMT+2",
    "Cabo Verde": "GMT-1",
    "Cambodia": "GMT+7",
    "Cameroon": "GMT+1",
    "Canada": "GMT-5", // Default (Toronto/Montreal)
    "Central African Republic": "GMT+1",
    "Chad": "GMT+1",
    "Chile": "GMT-3",
    "China": "GMT+8",
    "Colombia": "GMT-5",
    "Comoros": "GMT+3",
    "Congo (Congo-Brazzaville)": "GMT+1",
    "Costa Rica": "GMT-6",
    "Croatia": "GMT+1",
    "Cuba": "GMT-5",
    "Cyprus": "GMT+2",
    "Czechia (Czech Republic)": "GMT+1",
    "Denmark": "GMT+1",
    "Djibouti": "GMT+3",
    "Dominica": "GMT-4",
    "Dominican Republic": "GMT-4",
    "Ecuador": "GMT-5",
    "Egypt": "GMT+2",
    "El Salvador": "GMT-6",
    "Equatorial Guinea": "GMT+1",
    "Eritrea": "GMT+3",
    "Estonia": "GMT+2",
    "Eswatini": "GMT+2",
    "Ethiopia": "GMT+3",
    "Fiji": "GMT+12",
    "Finland": "GMT+2",
    "France": "GMT+1",
    "Gabon": "GMT+1",
    "Gambia": "GMT+0",
    "Georgia": "GMT+4",
    "Germany": "GMT+1",
    "Ghana": "GMT+0",
    "Greece": "GMT+2",
    "Grenada": "GMT-4",
    "Guatemala": "GMT-6",
    "Guinea": "GMT+0",
    "Guinea-Bissau": "GMT+0",
    "Guyana": "GMT-4",
    "Haiti": "GMT-5",
    "Honduras": "GMT-6",
    "Hungary": "GMT+1",
    "Iceland": "GMT+0",
    "India": "GMT+5:30",
    "Indonesia": "GMT+7", // Western
    "Iran": "GMT+3:30",
    "Iraq": "GMT+3",
    "Ireland": "GMT+0",
    "Israel": "GMT+2",
    "Italy": "GMT+1",
    "Jamaica": "GMT-5",
    "Japan": "GMT+9",
    "Jordan": "GMT+3",
    "Kazakhstan": "GMT+6",
    "Kenya": "GMT+3",
    "Kiribati": "GMT+14",
    "Korea (North)": "GMT+9",
    "Korea (South)": "GMT+9",
    "Kosovo": "GMT+1",
    "Kuwait": "GMT+3",
    "Kyrgyzstan": "GMT+6",
    "Laos": "GMT+7",
    "Latvia": "GMT+2",
    "Lebanon": "GMT+2",
    "Lesotho": "GMT+2",
    "Liberia": "GMT+0",
    "Libya": "GMT+2",
    "Liechtenstein": "GMT+1",
    "Lithuania": "GMT+2",
    "Luxembourg": "GMT+1",
    "Madagascar": "GMT+3",
    "Malawi": "GMT+2",
    "Malaysia": "GMT+8",
    "Maldives": "GMT+5",
    "Mali": "GMT+0",
    "Malta": "GMT+1",
    "Marshall Islands": "GMT+12",
    "Mauritania": "GMT+0",
    "Mauritius": "GMT+4",
    "Mexico": "GMT-6", // Default(Mexico City)
    "Micronesia": "GMT+11",
    "Moldova": "GMT+2",
    "Monaco": "GMT+1",
    "Mongolia": "GMT+8",
    "Montenegro": "GMT+1",
    "Morocco": "GMT+1",
    "Mozambique": "GMT+2",
    "Myanmar (formerly Burma)": "GMT+6:30",
    "Namibia": "GMT+2",
    "Nauru": "GMT+12",
    "Nepal": "GMT+5:45",
    "Netherlands": "GMT+1",
    "New Zealand": "GMT+12",
    "Nicaragua": "GMT-6",
    "Niger": "GMT+1",
    "Nigeria": "GMT+1",
    "North Macedonia": "GMT+1",
    "Norway": "GMT+1",
    "Oman": "GMT+4",
    "Pakistan": "GMT+5",
    "Palau": "GMT+9",
    "Palestine State": "GMT+2",
    "Panama": "GMT-5",
    "Papua New Guinea": "GMT+10",
    "Paraguay": "GMT-3",
    "Peru": "GMT-5",
    "Philippines": "GMT+8",
    "Poland": "GMT+1",
    "Portugal": "GMT+0",
    "Qatar": "GMT+3",
    "Romania": "GMT+2",
    "Russia": "GMT+3", // Moscow
    "Rwanda": "GMT+2",
    "Saint Kitts and Nevis": "GMT-4",
    "Saint Lucia": "GMT-4",
    "Saint Vincent and the Grenadines": "GMT-4",
    "Samoa": "GMT+13",
    "San Marino": "GMT+1",
    "Sao Tome and Principe": "GMT+0",
    "Saudi Arabia": "GMT+3",
    "Senegal": "GMT+0",
    "Serbia": "GMT+1",
    "Seychelles": "GMT+4",
    "Sierra Leone": "GMT+0",
    "Singapore": "GMT+8",
    "Slovakia": "GMT+1",
    "Slovenia": "GMT+1",
    "Solomon Islands": "GMT+11",
    "Somalia": "GMT+3",
    "South Africa": "GMT+2",
    "South Sudan": "GMT+2",
    "Spain": "GMT+1",
    "Sri Lanka": "GMT+5:30",
    "Sudan": "GMT+2",
    "Suriname": "GMT-3",
    "Sweden": "GMT+1",
    "Switzerland": "GMT+1",
    "Syria": "GMT+3",
    "Taiwan": "GMT+8",
    "Tajikistan": "GMT+5",
    "Tanzania": "GMT+3",
    "Thailand": "GMT+7",
    "Timor-Leste": "GMT+9",
    "Togo": "GMT+0",
    "Tonga": "GMT+13",
    "Trinidad and Tobago": "GMT-4",
    "Tunisia": "GMT+1",
    "Turkey": "GMT+3",
    "Turkmenistan": "GMT+5",
    "Tuvalu": "GMT+12",
    "Uganda": "GMT+3",
    "Ukraine": "GMT+2",
    "United Arab Emirates": "GMT+4",
    "United Kingdom": "GMT+0",
    "United States of America": "GMT-5", // EST
    "Uruguay": "GMT-3",
    "Uzbekistan": "GMT+5",
    "Vanuatu": "GMT+11",
    "Vatican City": "GMT+1",
    "Venezuela": "GMT-4",
    "Vietnam": "GMT+7",
    "Yemen": "GMT+3",
    "Zambia": "GMT+2",
    "Zimbabwe": "GMT+2"
};

export const getTimezone = (country: string, city: string = ""): string => {
    // Basic overrides for large countries based on City
    const cityLower = city.toLowerCase();

    if (country === "United States of America") {
        if (cityLower.includes("los angeles") || cityLower.includes("san francisco") || cityLower.includes("seattle") || cityLower.includes("san diego")) return "GMT-8";
        if (cityLower.includes("denver") || cityLower.includes("phoenix")) return "GMT-7";
        if (cityLower.includes("chicago") || cityLower.includes("houston") || cityLower.includes("dallas")) return "GMT-6";
        return "GMT-5"; // Default EST
    }

    if (country === "Canada") {
        if (cityLower.includes("vancouver")) return "GMT-8";
        if (cityLower.includes("calgary") || cityLower.includes("edmonton")) return "GMT-7";
        return "GMT-5";
    }

    if (country === "Australia") {
        if (cityLower.includes("perth")) return "GMT+8";
        if (cityLower.includes("adelaide")) return "GMT+9:30";
        return "GMT+10";
    }

    if (country === "Brazil") {
        if (cityLower.includes("manaus")) return "GMT-4";
        return "GMT-3";
    }

    return defaultTimezones[country] || "";
};
